name: continuous integration
on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/**.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout my repository
        uses: actions/checkout@v6
      
      - name: setup python
        uses: actions/setup-python@v6
        with:
          "python-version": "3.12"

      - name: install dependencies
        run: pip install -r requirements.txt
      
      - name: run test cases
        run: pytest
